/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.metamechanists.org/releases/")
    }

    maven {
        url = uri("https://repo.destroystokyo.com/repository/maven-public/")
    }

    maven {
        url = uri("https://jitpack.io")
    }

    maven {
        url = uri("https://repo.dmulloy2.net/repository/public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.metamechanists:MetaLib:46")
    api("org.metamechanists:DisplayModelLib:14")
    compileOnly("io.papermc.paper:paper-api:1.19.4-R0.1-SNAPSHOT")
    compileOnly("org.projectlombok:lombok:1.18.24")
    compileOnly("com.github.Slimefun:Slimefun4:ddb7ebd134")
    compileOnly("com.comphenix.protocol:ProtocolLib:5.1.0")
}

group = "org.metamechanists"
version = "0"
description = "Aircraft"
java.sourceCompatibility = JavaVersion.VERSION_16

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}
