name: Aircraft
version: '${project.version}'
author: Idra
main: org.metamechanists.aircraft.Aircraft
api-version: 1.19

depend:
  - Slimefun

commands:
  aircraft:
    description: /aircraft
    usage: /aircraft <subcommand>

permissions:
  aircraft.command.reload:
    default: op
    description: Reloads the plugin